[fixup]: ramips: fix patch asoc sound
No thorough check that this is valid

sound/soc/ralink/ralink-i2s.c: In function 'ralink_i2s_init_dma_data':
sound/soc/ralink/ralink-i2s.c:452:17: error: 'struct
snd_dmaengine_dai_dma_data' has no member named 'slave_id'
  452 |         dma_data->slave_id = i2s->txdma_req;
      |                 ^~
sound/soc/ralink/ralink-i2s.c:462:17: error: 'struct
snd_dmaengine_dai_dma_data' has no member named 'slave_id'
  462 |         dma_data->slave_id = i2s->rxdma_req;
      |                 ^~

3c2196440757 ("dmaengine: remove slave_id config field") 6.1
https://lore.kernel.org/lkml/20211122222203.4103644-1-arnd@kernel.org/

Signed-off-by: John Thomson <git@johnthomson.fastmail.com.au>